name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  push_to_registries:
    name: build compile images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build compile angular
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfile/angular
          file: ./dockerfile/angular/Dockerfile
          push: true
          tags: ttbb/compile:angular
          platforms: linux/amd64,linux/arm64
      - name: build compile c
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfile/c
          file: ./dockerfile/c/Dockerfile
          push: true
          tags: ttbb/compile:c
          platforms: linux/amd64,linux/arm64
      - name: build compile go
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfile/go
          file: ./dockerfile/go/Dockerfile
          push: true
          tags: ttbb/compile:go
          platforms: linux/amd64,linux/arm64
      - name: build compile goc
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfile/goc
          file: ./dockerfile/goc/Dockerfile
          push: true
          tags: ttbb/compile:goc
          platforms: linux/amd64,linux/arm64
      - name: build compile jdk8 git
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfile/jdk8-git
          file: ./dockerfile/jdk8-git/Dockerfile
          push: true
          tags: ttbb/compile:jdk8-git
          platforms: linux/amd64,linux/arm64 
      - name: build compile jdk8 git gradle
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfile/jdk8-git-gradle
          file: ./dockerfile/jdk8-git-gradle/Dockerfile
          push: true
          tags: ttbb/compile:jdk8-git-gradle
          platforms: linux/amd64,linux/arm64                   
      - name: build compile jdk8 git mvn
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfile/jdk8-git-mvn
          file: ./dockerfile/jdk8-git-mvn/Dockerfile
          push: true
          tags: ttbb/compile:jdk8-git-mvn
          platforms: linux/amd64,linux/arm64
      - name: build compile jdk11 git
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfile/jdk11-git
          file: ./dockerfile/jdk11-git/Dockerfile
          push: true
          tags: ttbb/compile:jdk11-git
          platforms: linux/amd64,linux/arm64 
      - name: build compile jdk11 git gradle
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfile/jdk11-git-gradle
          file: ./dockerfile/jdk11-git-gradle/Dockerfile
          push: true
          tags: ttbb/compile:jdk11-git-gradle
          platforms: linux/amd64,linux/arm64                   
      - name: build compile jdk17 git
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfile/jdk17-git
          file: ./dockerfile/jdk17-git/Dockerfile
          push: true
          tags: ttbb/compile:jdk17-git
          platforms: linux/amd64,linux/arm64   
      - name: build compile jdk17 git gradle
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfile/jdk17-git-gradle
          file: ./dockerfile/jdk17-git-gradle/Dockerfile
          push: true
          tags: ttbb/compile:jdk17-git-gradle
          platforms: linux/amd64,linux/arm64                 
      - name: build compile jdk17 git mvn
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfile/jdk17-git-mvn
          file: ./dockerfile/jdk17-git-mvn/Dockerfile
          push: true
          tags: ttbb/compile:jdk17-git-mvn
          platforms: linux/amd64,linux/arm64
      - name: build compile rust
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfile/rust
          file: ./dockerfile/rust/Dockerfile
          push: true
          tags: ttbb/compile:rust
          platforms: linux/amd64,linux/arm64
      - name: build compile scala
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfile/scala
          file: ./dockerfile/scala/Dockerfile
          push: true
          tags: ttbb/compile:scala
          platforms: linux/amd64,linux/arm64
